version: "3"

services:
  stationeers:
    image: ghcr.io/JohnVidler/docker-stationeers:latest
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      VISIBLE:       true
      NAME:          "Docker Stationeers"
      DEFAULT_WORLD: "moon"
      PASSWORD:      "password"
      MAX_PLAYERS:   10
    ports:
      - "27015:27015/udp"
      - "27016:27016/udp"
      - "8081:8081/tcp"
    volumes:
      - ./data/saves:/home/steam/stationeers/saves
      - ./data/scripts:/home/steam/stationeers/scripts
