services:
  stationeers:
    #image: docker-stationeers:bepinex
    build: .
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      SV_VISIBLE:       true
      SV_NAME:          "Docker Stationeers - EVIL THIS ONE"
      SV_DEFAULT_WORLD: "Moon"
      SV_PASSWORD:      "private"
      SV_MAX_PLAYERS:   10
    ports:
      - "27015:27015/udp"
      - "27016:27016/udp"
      - "27015:27015"
      - "27016:27016"
      - "8081:8081/tcp"
    volumes:
      - ./data:/home/steam/stationeers/saves
      - ./BepInEx:/home/steam/stationeers/BepInEx
      - ./modlist.txt:/home/steam/stationeers/modlist.txt
      - ./mods:/home/steam/stationeers/mods
