#!/bin/bash

pushd "${STEAM_APP_PATH}"

# Do we have a config directory yet?
if [ ! -f BepInEx/config/BepInEx.cfg ]; then
    echo "Running first-time BepInEx setup"

    if [ ! -f "BepInEx_linux_x64_${MOD_BEPINEX_VERSION}.zip" ]; then
        echo "Downloading BepInEx version ${MOD_BEPINEX_VERSION}"
        curl -LO "https://github.com/BepInEx/BepInEx/releases/download/v${MOD_BEPINEX_VERSION}/BepInEx_linux_x64_${MOD_BEPINEX_VERSION}.zip"
        unzip "BepInEx_linux_x64_${MOD_BEPINEX_VERSION}.zip"
    fi

    pushd "BepInEx/plugins"
    if [ ! -f StationeersMods.zip ]; then
        echo "Downloading StationeersMods version ${MOD_STATIONEERSMODS_VERSION}"
        curl -LO "https://github.com/jixxed/StationeersMods/releases/download/v${MOD_STATIONEERSMODS_VERSION}/StationeersMods.zip"
        unzip "StationeersMods.zip"
    fi
    popd

    # Update the runner script to have our executable
    sed -i 's/^executable_name=""$/executable_name="rocketstation_DedicatedServer.x86_64"/' run_bepinex.sh
    chmod u+x run_bepinex.sh
else
    echo "BepInEx already present, skipped"
fi

popd
